apiVersion: v1
kind: Namespace
metadata: 
  name: diploma
  labels: 
    name: diploma

---
# mysql-service.yaml 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service
  name: mysql-service
  namespace: diploma  
spec:
  externalName: DB_HOST
  selector:
    app: mysql-service
  type: ExternalName
status:
  loadBalancer: {}    

---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: diploma
  labels:
    app: back
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - image: AWS_ID.dkr.ecr.AWS_DEFAULT_REGION.amazonaws.com/IMAGE_REPO_NAME:IMAGE_TAG
        name: back
        ports:
        - containerPort: 5000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1           

---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: diploma
spec:
  type: LoadBalancer
  selector:
    app: back
  ports:
    - name: http
      protocol: TCP
      port: 8050
      targetPort: 5000