apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: diploma
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - image: AWS_ID.dkr.ecr.AWS_DEFAULT_REGION.amazonaws.com/IMAGE_REPO_NAME:IMAGE_TAG
        name: front
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: diploma
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: back
            port:
              number: 80